# Site settings
email: luke@techwriterluke.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Writing In Tech
description: A blog focused on technical writing, but also other stuff.
url: "https://techwriterluke.com"
twitter_username: techluke
default_img: 

# Profile settings
name: Luke Haviland
profile_img: 
profile: Technical Writing and other things.
social:
  github: 
  facebook: http://facebook.com/techluke

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
